chg: Transition 3Box integration to Ceramic.
unioncredit/union-v1-interface pull request #133
Opened 2021-07-08 11:24 UTC by twygod

2021-07-09 10:58 UTC, maxweng approved these changes

2021-07-09 11:04 UTC, arthcp approved these changes

2021-07-09 22:27 UTC, kingjacob requested changes
It's not pulling any of the 3Box profiles for accounts i know have 3Box info present, while on kovan. I think the issue is the "chainid"? Profile info should be the same for L1, Kovan, Polygon since it's the same key. 

I'm also not seeing any ENS names either now as well, which this shouldn't have affected.

2021-07-29 11:21 UTC, twygod commented
> It's not pulling any of the 3Box profiles for accounts i know have 3Box info present, while on kovan. I think the issue is the "chainid"? Profile info should be the same for L1, Kovan, Polygon since it's the same key.
> 
> I'm also not seeing any ENS names either now as well, which this shouldn't have affected.

Mainnet data used

2021-11-18 12:26 UTC, GeraldHost commented
Going to close some of these pull request that are old and inactive.
also we are just going to be using ENS going forward.

2021-11-18 12:26 UTC, closed without merging