chg: Modify the logic of using dai permit.
unioncredit/union-v1-interface pull request #154
Opened 2021-07-27 06:21 UTC by twygod

2021-07-29 11:39 UTC, arthcp requested changes

2021-07-29 11:39 UTC, arthcp commented on hooks/payables/useStakeDeposit.ts
> +          console.log("err", err);
The console log can be removed

2021-07-29 11:39 UTC, arthcp commented on hooks/payables/useDaiPermit.ts
> +      if (chainId === 1 || chainId === 4) {
Permit should work for Polygon network also

2021-07-30 07:06 UTC, twygod commented on hooks/payables/useDaiPermit.ts
> +      if (chainId === 1 || chainId === 4) {
> Permit should work for Polygon network also

There are some differences between the dai on Polygon and the dai on the mainnet. The eth-permit plug-in used now is designed for the dai of the main network. The permit cannot be signed on Polygon, so first deal with the error like this

2021-07-30 12:28 UTC, arthcp commented on hooks/payables/useDaiPermit.ts
> +      if (chainId === 1 || chainId === 4) {
Can you tell how they are different exactly? 
We should at least add logic to use different permit on polygon instead of not supporting it.

2021-07-30 12:34 UTC, arthcp commented on hooks/payables/useDaiPermit.ts
> +      if (chainId === 1 || chainId === 4) {
i'm pretty sure DAI permit should be same as ethereum mainnet.

https://github.com/maticnetwork/pos-portal/blob/master/contracts/child/ChildToken/DappTokens/UChildDAI.sol
https://github.com/makerdao/dss/blob/master/src/dai.sol

2021-08-13 07:10 UTC, twygod commented on hooks/payables/useDaiPermit.ts
> +      if (chainId === 1 || chainId === 4) {
The definition of DOMAIN_SEPARATOR and getDomainSeperator() is different, and UChildDAI uses getNonce to obtain nonces, and dai uses nonces directly.

2021-08-13 07:16 UTC, twygod commented on hooks/payables/useDaiPermit.ts
> +      if (chainId === 1 || chainId === 4) {
[https://imgur.com/a/4uDBGx5](https://imgur.com/a/4uDBGx5)

2022-01-31 21:26 UTC, closed without merging