feature/uni-247-add-polygon-network-switcher-and-auto
unioncredit/union-v1-interface pull request #160
Opened 2021-08-06 22:23 UTC by arthcp

2021-08-13 18:52 UTC, kingjacob requested changes

2021-08-13 18:52 UTC, kingjacob commented on components/MetamaskNetworkIndicator/index.js
> +  42: { name: "Kovan", logo: "/images/ethereum-logo.png" },
Each Testnet does have their own logo ie kovans is a tram. But for simplicity, I think we just leave the top bar if it's not dealing with real money. ie all networks not mainnet or polgon.

2021-08-14 12:35 UTC, GeraldHost commented on components/MetamaskSwitcher/index.js
> +  });
Do you want to include a dependency array to this useEffect? At the moment a listener will attach to `chainChanged` every-time this component re-renders. I think an empty array will do here:
```js
useEffect(() => {}, []);
```

2021-08-14 12:40 UTC, GeraldHost commented on components/MetamaskSwitcher/index.js
> +    setTimeout(() => {
It would be neat to make sure any timers are cleaned up when the component un-mounts. We could have a situation where the component has unmounted but the timer function is trying to call a state update on an unmounted component. This pattern is a nice way to handle this:

```js
// create a ref to hold the timer ID
const timer = useRef(null);

const handleChangeNetwork = async () => {
  ...
  // assign the timer ID to the ref
  timer.current = setTimeout(() => { ... }, 1000);
}

useEffect(() => {
  return () => {
    // clean up the timer when the component un-mounts
    timer.current && clearTimeout(timer.current);
  }
}, []);
```

2021-08-16 09:23 UTC, arthcp commented on components/MetamaskSwitcher/index.js
> +    setTimeout(() => {
Done!

2021-08-16 23:13 UTC, kingjacob approved these changes

2021-08-17 08:14 UTC, merged